
# FREQUENT TYPOS WHERE WE CAN JUST REPLACE THEM REGARDLESS OF THE WORDS BEFORE AND AFTER (i.e. we are very confident that this is what they should be)
# THERE IS NOTHING ELSE IT COULD POSSIBLY BE

library(magrittr)
library(tidyverse)

typos_clear <- dplyr::tribble(
  ~correct, ~typos,
  "Dennis", "Denhis",
  "Butch Otter", "Butch” Otter",
  "Hillary Rodham Clinton", "Hillary Rodham Clintor",
  "Wood Hassan", "W. Hassan",
  "Randall", "Rendell",
  "Miller", "Milller",
  "Baldwin", "Balwin",
  "Darrell", "(Dafrell|Darrelll)",
  "Darrell Issa", "DarrelUssa",
  "Tom Udall", "TomUdall",
  "DOGGETT", "DOGGET\\b",
  "Nick J", "NickJ\\b",
  "Labrador", "Labradoe",
  "Tammy", "Tammv",
  "Jim", "\\bJ im\\b",
  "Richard", "Ricard\\b",
  "BARR", "\\bBafr\\b",
  "Doris", "\\\bD oris\\b",
  " O ", "( 0 | 0, )",
  "Justin", "Justirt\\b",
  "Thornberry", "Thomberry",
  "BUERKLE", "Beurkle",
  "NAPOLITANO","na politano",
  "Hutchison", "Hutchis$",
  "NADLER", "NA DLER",
  "Emanuel", "Emanual",
  "RENACCI", "RE CCI",
  "BYRNE", "Byme",
  "Rockefeller", "Rockefe ller",
  "jose serrano","jose. serrano",
  "biggert", "bigger!", #SSA OCR
  "Benjamin", "Ben jamin",#FTC
  "Nelson", "Ne lson", #FTC
  "FILNER, B", "FILNERB", #OSDJDS
  "merkley", "merkely",
  "SOUDER, M", "SOUDERM", # all of the ones like this are from OSDJS, may want to move to that script
  "HALL, J", "HALLJ",
  "RANGEL, C", "RANGELC",
  "TURNER, M", "TURNERM",
  "TIAHRT, T", "TIAHRl, T", # this is a OCR error, but unclear what the universal fix would be
  "BOCCIERI, J", "BOCCIERL, J",
  "BONNER, J", "BONNERJ",
  "FRANK, B", "FRANKB",
  "GOHMERT, L", "GOHMERl, L",
  "VISCLOSKY", "VlSCLOSKY",
  "SCHAKOWSKY","SCHAKOWSKl",
  "HOYER, S", "HOYERS",
  "KANJORSKI","KANJORSKL",
  "Grassley", "(Grassely|Grassle\\b|Grassleyy)",
  "DEAL, N", "DEAL,N",
  "senator cortez masto", "senator masto",
  "GILLIBRAND", "GILLABRAND",
  "WENSTRUP", "WENSTRUB",
  "BUTTERFIELD, G.K." ,"BUTTERFIELD, G. K.", # silly but this is how it is in voteview
  "G.K. BUTTERFIELD" ,"G. K. BUTTERFIELD", # silly but this is how it is in voteview
  "Diaz Barragan", "(D.az Barrag.n|D.az Barrag..n)",
  "FEINGOLD", "FEINGOL\\b", #FIXME - should just be not D
  "FILNER, B", "FILNERB",
  "Butterfield, G K", "Butterfield, GK",
  "EDWARDS, DONNA", "EDWARD, DONNA",
  "Andre Carson", "Andre' Carson",
  #"GOHMERT, L", "GOHMERT. L", # period space is corrected in ocr errors
  #"SESTAK, J", "SESTAK. J",
  "OBEY, D", "OBEYD",
  "OBEY, D", "OBEY,D",
  "Gassley ", "(Grassle y|Grassle )", # space is key or it will add a space and Y
  "Thune, John", "ThuneJohn",
  "Cummings", "(Cummins|Cwnmings)",
  "Ellmers", "Ellrners",
  "TONKO", "TONKA",
  "BLUMENAUER", "blume uer",
  "Darrell Issa", "DarrellIssa",
  "Phil ", "Phill ", # I added a space because it seems risky to match Phill...
  "LaMalfa", "LaMalfn",
  "Courtey", "Courntney",
  "Gerlach", "Gerlah",
  "Darlene", "Darene",
  "Elizabeth", "Elezabeth",
  "Jeffrey", "Jeflrey",
  "Barbara", "(Babara|Barabara)",
  "Velazquez", "Vel.zquez",
  "MacArthur","(Mcarthur|Mccarthur)", # there is no McArthur in members file
  "Martin","Martrin",
  "VISCLOSKY", ".isclosky",
  "Murphy", "Murhpy",
  "Fitzpatrick", "Fitzpatric\\b",
  "DeFazio", "Def azio",
  "Inslee", "lnslee", # OCR error, e.g. in FTC
  "Sanchez", "S.nchez",
  "Gutierrez", "(Guitierrez|GUTI.RREZ|Gut.errez)",
  "Melissa", "Melisssa",
  "Brian", "Brain",
  "Christopher", "Christoher",
  "Raul", "R.ul",
  "Charles", "Charkes",
  "Benjamin", "Bemjamin",
  "McCaskill", "McCaskil$",
  "McCaskill,", "McCaskil,",
  "McCaskill ", "McCaskil ",
  "Luetkemeyer", "(Leutkemeyer|Leautkemeyer|Luektemeyer)",
  "Herrera Beutler", "(Herrera-Beutler|Harrera Beutler)",
  "Michael", "(Midlael|Michaell|Micahel)",
  "SHERRILL", "Sheril",
  "Moolenaar", "(Molinar|Moolenar)",
  "Perlmutter", "Perimutter",
  "Manzullo", "Manzulo",
  "NEUGEBAUER", "BEUGEBAUER",
  "INHOFE, JAMES", "INHOFEJAMES",
  "BAUCUS, MAX", "8AUCUS, MAX",
  "BINGAMAN, JEFF", "BINGAMAN JEFF",
  "KYL, JON", "KYL JON",
  "MCCAIN, JOHN", "MCCAIN JOHN",
  "CANTWELL, MARIA","CANTWELL MARIA",
  "YOUNG, DON","YOUNG. DON",
  "Van Hollen, Chris","Hollen, Chris Van",
  "Chip Pickering", "\\(Chip\\) Pickering",
  "Frelinghuysen", "Frelinghuyse\\b",
  "Butch Otter", "\\(Butch\\) Otter",
  "Kit Bond", "\"Kit\" Bond",
  "Duke Cunningham", "\\(Duke\\) Cunningham",
  "Bachmann", "Bachman\\b",


  #"Diaz-Balart", "(Diaz($|,)|Balart($|,))", #still not working for whatever reason
  #FIXME

  ###############################

  # Reversing order of first name and last name
  # Added the missing commas so they match the last, first pattern
  "Duncan, John", "Duncan John",
  "Johnson, Henry", "Johnson Henry",
  "Bono, Mary", "Bono Mary",
  "Rahall, Nick", "Rahall Nick",
  "Jackson Lee", "(Lee Jackson|Jackson-Lee)",
  "Westerman", "Westeman", #SSA
  "Conaway, Michael", "Conaway Michael",
  "Griffith, Morgan", "Griffith Morgan",
  "Womack, Steve", "Womack Steve",
  "ROHRABACHER, Dana", "ROHRABACHER Dana",
  "Nelson, Ben", "Nelson Ben",
  "Ryan, Paul", "Ryan Paul",
  "Chao, Elaine", "Chao Elaine",
  "Miller, George", "Miller George",
  "Herrera Beutler, Jaime", "Herrera Beutler Jaime",
  "Conyers, John", "Conyers John",
  "UDALL, TOM", "UDALL TOM",
  "Sensenbrenner, James", "Sensenbrenner James",
  "Pittenger, Robert", "Pittenger Robert"

)

# FREQUENT LAST NAME TYPOS WHERE WE ALSO WANT TO SEE THE FIRST NAME
typos_last <- dplyr::tribble(
  ~first_name, ~last_name, ~last_name_typos,
  "Richard", "Hanna", "Han\\b",
  "Mark", "Pocan", "Pecan",
  "Grace", "Meng", "Ming",
  "Aaron", "Schock", "S chock",
  "Nita", "LOWEY", "Lewey",
  "Sean Patrick", "Maloney", "Malone\\b",
  "Stephanie Tubbs", "Jones", "Jone\\b",
  "Larry", "Bucshon", "Buchon",
  "Barbara", "Cubin", "Gubin",
  "Bradley", "BYRNE", "Byne",
  "Dutch", "RUPPERSBERGER", "Ruppersberge\\b",
  "Heath", "Shuler", "Schuler",
  "Glenn", "Grothman", "Grotham",
  "Jaime", "Herrera Beutler", "(Herrera|Beutler)",
  "Harold", "Rogers", "Rodgers",
  "Nick", "Rahall", "Rahail",
  "Patty", "Murray", "(Murrary|Muray)",
  "Lois", "Capps", "Crapps",
  "Rick", "Boucher", "Bocuher",
  "Robert", "Andrews", "Andrew",
  "Rodney", "Frelinghuysen", "(Frelinguysen|Frelinghuyser|Frelinhuysen)",
  "Shelley", "Berkley", "Barkley",
  "Steny", "Hoyer", "Royer",
  "Vito", "Fossella", "Fosella",
  "John", "Barrasso", "Barasso",
  "Larry", "Bucshon", "Bueston",
  "Matt", "Cartwright", "Cartwrite",
  "Rosa", "DeLauro", "De Lauro",
  "Mike", "DeWine", "De Wine",
  "Michael", "Bilirakis", "Bilikaris",
  "Jack", "Reed", "Red",
  "David", "Schweikert", "Schweikerl",
  "Peter", "DeFazio", "DiFazio",
  "Roy", "Blunt", "Blur",
  "Steve", "Scalise", "(Scalisse|Scallise)",
  "Russ", "Carnahan", "(Carnhan|Camahan)",
  "Zoe", "Lofgren", "Lufgren",
  "Thomas", "Holden", "Holen",
  "Olympia","Snowe", "Showe",
  "Robert","Byrd", "Bryd",
  "Michael", "Honda",  "Honds",
  "Lois", "Capps", "Caps",
  "Joseph", "Crowley", "(Crowly|Cowley)",
  "Joseph", "Lieberman", "Liberman",
  "Juanita", "Millender-McDonald", "Millender-McDonal",
  "John", "Shimkus", "(Shimku|Slimkus)",
  "John", "Sullivan", "Sulivan",
  "Jon", "Porter", "(Poster|Parter)",
  "David", "Cicilline", "Cicillin",
  "David", "Vitter", "(Vitters|Vilter)",
  "Debbie", "Stabenow", "(Stebenow|Stabeno|Stavenow)",
  "Dianne", "Feinstein", "(Feinsten|Feinstein|Feinstien|Fenstein)",
  "Don", "Nickles", "Nickels",
  "Doug", "Lamborn", "(Lamborg|Lambon)",
  'Edward', "Markey", "Marley",
  "Jery", 'Costello', "Costelo",
  "Jerry", "Kleczka", "Kyleczka",
  "John", "Barrow", "Barroy",
  "Jeff", "Merkley", "(Merkly|Merkeley)",
  "James", "Jeffords", "(Jefford|Jeffers)",
  "Jack", "Kingston", "Kington",
  "Greg", "Walden", "Wilden",
  "George","Radanovich", "(Radanovich|Radavich|Radnovich)",
  "George", "Nethercutt", "Nethecutt",
  "Frank", "Murkowski", "(Murkowsk|Mukowski)",
  "Marcy", "Kaptur", "Kaptor",
  "Bob", "Goodlatte", "(Godlatte|Goodlat)",
  "Dutch", "Ruppersberger", "Rupperberger",
  "Carolyn", "Maloney", "Malony",
  "Charles", "Rangel", "Ranger",
  "Christopher", "Van Hollen", "(VANHOLLEN|Van Kollen|Hollen)",
  "Gary", "Ackerman", "Acherman",
  "Conrad", "Burns", "Bums",
  "John", "Hostettler", "Hostetler",
  "Amy", "Klobuchar", "Klobachur|Klobachar",
  "Raja", "Krishnamoorthi", "(Krishnamoortni|Krishnamoothi)",
  "Barbara", "Mikulski", "(Mukulski|Milkulski)",
  "Ruben", "Hinojosa", "Hinohosa",
  "George", "Lemieux", "Lemieuz",
  "Tom", "Periello", "Perielo",
  "Stephanie", "Herseth Sandlin", "(Herseth|Sandlin)",
  "John", "ROCKEFELLER", "(Rockefellar|ROCKFELLER)",
  "Ron", "Wyden", "Wydon",
  "John", "Cornyn", "(Comyn|Com yn|Corvyn|Coryn)",
  "Joe", "Manchin", "Machin",
  "Blake", "Farenthold", "(Farenhold|Farenthod|Farentold)",
  "Anna", "Eshoo", "Eschoo",
  "Heidi", "Heitkamp", "(Heitkkamp|Heitkmap|Heitkamps)",
  "Gerry", "Connolly", "Connelly",
  "Anthony", "Gonzalez", "Gonzales",
  "James", "Inhofe", "(Inholfe|Imhofe|Imholfe|Inhoffe|Lnhofe|Tnhofe)",
  "Yvette", "Clarke", "Clark",
  "Maurice", "Hinchey", "Henchey",
  "Chaka", "Fattah", "Chakka",
  "Kirsten", "Gillibrand", "(Gillebrand|Gillbrand)",
  "James","Barrett", "(Barrat|Barret)",
  "Lucille", "ROYBAL-ALLARD", "(Allard|Roybal)",
  "James", "Barrett", "(GRESHAM|BARRETT)",
  "Catherine", "CORTEZ MASTO", "(CORTEZ|MASTO|MATSO|Cortez Mastro|Cortez Nasto|Cortez-Masto)",
  "Thomas","Coburn","(Cobum|Co bum)",
  "Trent", "Kelly", "Key",
  "Robin", "Kelly", "Key",
  "Mike", "Kelly", "Key",
  "Jon","Kyl", "Kyi|Kyle",
  "Cliff", "Stearns","Steams",
  "Wayne", "Whitfield", "Whitefield",
  "Jane", "Harman", "Harmon",
  "Cathy", "McMORRIS RODGERS", "(McMorris|Rodgers|McMORRIS-RODGERS)",
  "James", "Barrett", "(Baret|Barett|Barret)",
  "Mario", "Diaz-Balart", "(Diaz|Balart)",
  "Lincoln", "Diaz-Balart", "(Diaz|Balart)",
  "Michelle", "Lujan Grisham", "(Grisham|Lujan|Lbuj.n Grishman|Lujan Grishar|Lujan Grish,|Grishar|Grish)",
  "Carol", "Shea-Porter", "(Shea|Porter|Shea Porter)",
  "Daniel", "Donovan", "Donavan",
  "Gloria", "Negrete McLeod", "(Negrete|McLeod)",
  "Sheila", "Jackson Lee", "(Jackson|Lee|Jackson-Lee)",
  "Ginny", "Brown-Waite", "(Brown|Waite|Brown Waite|BrownWaite)",
  "Bonnie", "Watson Coleman", "(Watson|Coleman)",
  "Beto", "O'Rourke", "(O Rourke|O.Rourke|Rourke|Orourke|O'Rouke)",
  "Barbara", "Boxer", "Baxter",
  "David", "Dreier", "Reier|Drier",
  "Kelly", "Ayotte", "Aytotte",
  "Steve", "King", "Kiing",
  "Peter", "King", "Kiing",
  "Angus", "King", "Kiing",
  "Martin", "Heinrich", "(Hienrich|Heinriech|Henrich)",
  "Ellen", "Tauscher", "Ianscher",
  "Jeff", "Bingaman", "(Bingman|Bingmen|Bingamen|Binghaman)",
  "Elizabeth", "Warren", "Varren",
  "Adam", "Schiff", "(Schif|Sdxiff)",
  "Robert", "TORRICELLI", "Toricelli",
  "Kay", "Hutchison", "Hutchinson",
  "Ann", "Kuster", "McLane",
  "Charles", "Grassley", "Grassly",
  "Slade", "Gorton", "Gordon",
  "Bob", "Franks", "Francks",
  "Mary", "Bono", "Bone",
  "Nancy", "Johnson", "Jonhson",
  "Paul", "COVERDELL", "Cordovell",
  "Tom", "DeLay", "De Lay",
  "Steve", "Pearce", "Peace",
  "Charlie", "Crist", "Christ",
  "Rick", "Crawford", "Crawfrod",
  "Robert", "BENNETT", "Bernnett",
  "Peter","DeFazio","De Fazio",
  "Paul", "Sarbanes", "Sabanes",
  "Mike", "McIntyre", "(McEntire|McLntyre)",
  "Margaret", "Hassan", "Hassen",
  "Michael", "Capuano", "Capuno",
  "Max","BAUCUS","Baucuz",
  "Jerry","Costello", "Costelo",
  "James", "Hansen", "Hansch",
  "Mac", "Thornberry", "Thomberry",
  "Michael", "Turner", "Tuner",
  "Doug", "Lamborn", "(Lambom|Lanborn)",
  "Bill", "Posey", "Posev",
  "Carl", "Levin", "Levine",
  "Mark", "Bennet", "Bennett",
  "Shelley", "Capito", "(MooreCapito|Moore-Capito|Capito Moore)",
  "Jeanne", "Shaheen", "(Shaneen|Shahenn)",
  "Debbie", "Wasserman Schultz", "(Schultz|Wasserman Shultz|Wasserman-Schultz|Wasserman-S|Wasserman-|Wasserman)",
  # FIXME #  last names hypenation can be a clear typo, but we can't just replace "Schultz"--that needs to be a last name typo (otherwise "Debbie Wasserman Schultz" will be replaced with "Debbie Wasserman Wasserman Schultz" and fail to match)
  # I deleted "Schultz" and moved it to a last name typos, but we may still have problems replacing "Wasserman-" like this (for example, "Wasserman-Schultz, Debbie" would be replaced with "Wasserman SchultzSchultz, Debbie and thus fail to match)
  "William", "Keating", "Keeting",
  "Mike", "Crapo", "Carpo",
  "Mark", "Desaulnier", "Desauliner",
  "Nanette", "Diaz Barragan", "Diaz-Barragan",
  "Bonnie", "Watson Coleman", "(Watson-Coleman|Coleman Watson)",
  "Adriano", "Espaillat", "Espaillet",
  "Tom", "O'Halleran", "O'Holleran",
  "Anthony", "BRINDISI", "Brindis",
  "Lisa", "BLUNT ROCHESTER", "BLUNT-ROCHESTER",
  "Bruce", "Braley", "Braly",
  "Marsha", "Blackburn", "Black burn",
  "Chris", "Collins", "Collings",
  "Scott", "Tipton", "Titpon",
  "Randy", "Weber", "Wever",
  "Randy", "Neugebauer","NEUGBAUER",
  "Johnny", "Isakson", "(Iskason|Isaakson)",
  "Deb", "FISCHER", "Fisher",
  "Ami", "Bera", "(Beta|Gera)",
  "Lynn", "WOOLSEY", "Woosley",
  "Roger", "Wicker", "Wickler",
  "David", "CICILLINE", "Cicillinc",
  "David", "Roe", "Roc",
  "Al", "Franken", "Fianken",
  "Arlen","Specter","Speeter",
  "Dana", "ROHRABACHER", "Rohrabaeher",
  "Mark", "Souder", "Sounder",
  "Maria", "Cantwell", "Catwell",
  "Earl", "Blumenauer", "Blumeanuer",
  "Jeff", "Fortenberry", "Fortenbery",
  "Neil", "Abercrombie", "Abercombie",
  "Robert", "Menendez", "(Mendez|Menedez)",
  "Earl", "Carter", "Cater",
  "Greg", "Gianforte", "Gianfote",
  "Lisa", "Murkowski", "Murkowsi",
  "Marco", "Rubio", "Robio",
  "Tom", "Harkin", "Harkins",
  "George", "Holding", "Holdings",
  "Marlin", "Stutzman", "(Stutzzman|Stutzmann)",
  "Jeff", "Flake", "Flakes",
  "Ben", "Lujan", "L.j.n",
  "Pete", "Aguilar", "Aguliar",
  "Sean", "Duffy", "Dufffy",
  "Charles", "Schumer", "Shumer",
  "Robert", "Hurt", "Hunt",
  "Randy", "Hultgren", "(Hultgreen|Hultgreeen)",
  "Eric", "Swalwell", "(Swallwell|Swalwell)",
  "Sherrod", "Brown", "Browns",
  "Tony", "Cardenas", "(Caedenas|C.rdenas)",
  "Mick", "Mulvaney", "Mulvancy",
  "Kathy", "Castor", "Caster",
  "Henry", "Cuellar", "Cueller",
  "Richard", "Durbin", "Dubin",
  "Bill", "Shuster", "Schuster",
  "Allyson", "Schwartz", "Schwaltz",
  "Ileana", "Ros-Lehtinen", "Lehtinen",
  "Jerry", "McNERNEY", "McNemey",
  "Michael", "Bennet", "Bennett",
  "John", "Conyers", "Conyer",
  "Kay", "Hagan", "Hagen",
  "Ed", "Whitfield", "Whitefield",
  "Mary", "Fallin", "FALUN",
  "Tom", "Udall", "(Uda ll|UDAU)",
  "Morgan", "Griffith", "Griffiths",
  "Jan", "Schakowsky", "Schakowski",
  "Ander", "Crenshaw", "Creshaw",
  "Mike", "FITZPATRICK", "Fitzpatick",
  "Brian", "Schatz", "Schartz",
  "Brian", "Bilbray", "Billbray",
  "Bradley", "Byrne", "Bryne",
  "Elise", "Stefanik", "Stefank",
  "John", "Delaney", "Delany",
  "Elizabeth", "Esty", "Etsy",
  "Thomas", "Tillis", "Tills",
  "James", "Himes", "Hines",
  "Frank", "Guinta", "Gulnta",
  "Saxby", "Chambliss", "Chabliss"










) %>%
  transmute(typos = str_c(str_c(first_name, "( | [A-z]* )", last_name_typos, "($| |,|;)"),
                          str_c(last_name_typos, ", ", first_name), sep = "|"),
            correct = paste(first_name, last_name))


# FREQUENT FIRST NAME TYPOS
typos_first <- dplyr::tribble(
  ~first_name, ~last_name, ~first_name_typos,
  "Tammy", "Baldwin", "Terry",
  "Wilbert", "TAUZIN", "WILLIAM", #speakermap
  "William", "CLAY", "WM",
  "Dean", "Heller", "Oean",
  "Mazie", "HIRONO", "Maize",
  "Ken", "CALVERT", "Kert",
  "Jaime", "Harrera Beutler", "Jamie",
  "Claudia", "Tenney", "Claudi",
  "Raul", "Grijalva", "Raúl",
  "jim gresham", "barrett", "j gresham",
  "Suzanne", "Kosmas", "Susanne",
  "Glenn", "Thompson", "Glen",
  "Raul", "Labrador", "Ra",
  "Stephen", "Lynch", "Steven",
  "Zoe", "Lofgren", "Toe",
  "Jeanne", "Shaheen", "(Joanne|Teanne)",
  "Ron", "Wyden", "Roy",
  "Russell", "Feingold", "(Russel|Rusell)",
  "Ric", "Keller", "Rick",
  "Orrin", "Hatch", "Orring",
  "Olympia", "Snowe", "Olymia",
  "Shelley", "Capito", "(Shelby|Shelly)",
  "Charles", "Schumer", "(Charls|Charls E)", # FIXME just adding middle initial for now, but eventually, it should be added to the typo pattern by merging with members data
  "Julia", "Carson", "Julie",
  "Tom", "Barrett", "Mark",
  "Matt", "Cartwright", "Mark",
  "Katherine", "Clark", "Kathrine",
  "Randy", "Weber", "Randay",
  "Nancy", "Pelosi", "Nanci",
  "Patrick", "Leahy", "Partrick",
  "Ralph", "Regula", "Raplh",
  "Chris", "Gibson", "Cris",
  "Ron", "Estes", "(John|Jon)",
  "Dean", "Heller", "Den",
  "Dennis", "Cardoza", "Dinnes",
  "Harry", "Reid", "Hary",
  "George", "Voinovich", "Geaorge",
  "Candice", "Miller", "(Candace|Candance)",
  "Cedric", "Richmond", "Cedic",
  "Christopher", "Smith", "Christoper",
  "Christopher", "Bond", "(Chritoper|Christoper)",
  "Chris", "Coons", "Cris",
  "Chris", "Stewart", "Cris",
  "Hillary", "Clinton", "(Hilllary|Hilary|Fillary)",
  "Filemon", "Vela", "Filimon",
  "Artur", "Davis", "Arthur",
  "Patrick", "Leahy", "Ted",
  "Harry", "Reid", "Marry",
  "Anna", "Eshoo", "(Ana|Anna A.)",
  "Darrell", "Issa", "(Darryl|Daryl|Darrel|Darel)",
  "Dianne", 'Feinstein', "Diane",
  "Eliot", "Engel", "Eliott",
  "Colin", "Allred", "Collin",
  "Collin", "Clark", "Colin",
  "Denise", "Majette", "Denis",
  "Dennis", "Ross", "Denis",
  "Dennis", "Cardoza", "Denis",
  "Dennis", "Moore", "Denis",
  "Dennis", "KUCINICH", "Denis",
  "Sheila", "Jackson Lee", "(Shelia|Shelee|Shelia Jackson)",
  "Jose", "Serrano", "Jos.",
  "Lindsey", "Graham", "Lindsay",
  "Andre", "Carson", "Andr.",
  "Corrine", "Brown", "Corinne",
  "Anna", "Eshoo", "Ana",
  "Vernon", "Ehlers", "Vermon",
  "Margaret", "Hassan", "Margret",
  "Angus", "King", "Argus",
  "Gary", "Ackerman", "Garry",
  "Jon", "Corzine", "John",
  "Renee", "Ellmers", "Renne",
  "Bart", "Stupak", "Bark",
  "Jane", "Harman", "James",
  "Byron", "Dorgan", "Bayron",
  "Ann", "Kuster", "Anne",
  "Maxine", "Waters", "Martina",
  "John", "Cornyn", "Jon",
  "William", "Clay", "(Wim|Wm.)",
  "William", "Tauzin", "WJ",
  "Kirsten", "Gillibrand", "(Kirstern|Kristen|Kirstine|Kirstein)",
  "Joe", "Barton", "Joel",
  "Christopher","Smith","C. NJ",
  "Richard", "Durbin", "Richad",
  "Debbie", "Wasserman Schultz", "Debbies",
  "David", "Kustoff", "Davis",
  "Conor", "Lamb", "Connor",
  "Rob", "Woodall", "Rod",
  "John", "Thune", "Jon",
  "Vicente", "Gonzalez", "Vincente",
  "Emanuel", "Cleaver", "(EMAUNEL|Emmanuel)",
  "Adriano", "Espaillat", "Adrian",
  "Cory", "Gardner", "Corey",
  "Maria", "Cantwell", "Marie",
  "Jim", "Himes", "Jime",
  "Julia", "Brownley", "Juila",
  "Carol", "Shea-Porter", "Carole",
  "Collin", "Peterson", "Colin",
  "Ron", "Barber", "Rob",
  "Michael", "Michaud", "Micha",
  "Nanette", "BARRAGAN", "Nannette",
  "Sanford", "Bishop", "Sandford",
  "Alcee", "Hastings", "(Alccc|Ateee)",
  "Arlen", "Specter", "(Alan|Alien|Arien)",
  "Bart", "Gordon", "Art",
  "Barney", "Frank", "Bamey",
  "Richard", "Shelby", "Ricard",
  "Ruben", "Hinojosa", "Rub.n",
  "Shelley", "Berkley", "Shelly",
  "Chris", "Collins", "Chirs",
  "Diane", "Black", "Diana",
  "Lloyd", "Doggett", "Llyod",
  "Elton", "Gallegly", "Wlton",
  "Barack", "Obama", "Brack",
  "Denny", "Rehberg", "Danny",
  "Christopher", "Murphy", "Chistopher",
  "Elijah", "Cummings", "Eluah",
  "Michael", "Conaway", "K. Michael",
  "Jon", "Tester", "John",
  "Lisa", "Murkowski", "Usa",
  "Donald", "MCEACHIN", "McEachin, A.Donald",
  "Byron", "Dorgan", "Bryon",
  "Orrin", "Hatch", "Orin",
  "Joseph", "Heck", "Joesph",
  "Jerry", "McNerney", "Jerr",
  "Cory", "Booker", "Corey",
  "Pramila", "Jayapal", "Primila",
  "Sander", "Levin", "Sandy"





)   %>%
  transmute(typos = str_c(str_c(first_name_typos, "( | [A-z]* )", last_name), # match any middle initial
                          str_c(last_name, ", ", first_name_typos), sep = "|" ),
            correct = paste(first_name, last_name))

# FREQUENT MIDDLE NAME TYPOS
typos_middle <-  dplyr::tribble(
  ~first_name, ~middle_name, ~last_name, ~middle_name_typos,
  "Hillary", "Rodham", "Clinton", "(Rodman|Redham)",
  "Benjamin", "Nighthorse", "Campbell", "(Nigbthorse|Nighhorse)",
  "Ben", "Nighthorse", "Campbell", "Nighhorse",
  "John", "Dennis", "Hastert", "Denis",
  "James", "Strom", "Thurmond", "Stom"
) %>%
  transmute(typos = str_c(paste(first_name, " ", middle_name_typos, " ", last_name),
                          str_c(last_name, ", ", first_name, " ", middle_name_typos), sep = "|"),
            correct = paste(first_name, middle_name, last_name))

# FREQUENT COMMON NAME TYPOS
typos_common_name <-  dplyr::tribble(
  ~common_name, ~last_name, ~common_name_typos,
  "Jon", "Corize", "John",
  "Joe", "Barton", "Joel",
  "Ben", "Cardin", "Bin",
  "Don", "Nickles", "Dob",
  "Don", "Young", "(Dong|Dob|Dan)",
  "Dennis", "Heck", "Denis",
  "Dennis", "Rehberg", "Denis"
) %>%
  transmute(typos = str_c(str_c(common_name_typos, "( | [A-z]* )", last_name),
                          str_c(last_name, ", ", common_name_typos), sep = "|"),
            correct = paste(common_name, last_name))

# FREQUENT MIDDLE INITIAL TYPOS
typos_middle_initial <- dplyr::tribble(
  ~first_name, ~middle_initial, ~last_name, ~middle_initial_typos,
  "Richard", "G", "Lugar", "D",
  "Roger", "F", "Wicker", "W",
  "Lindsey", "O", "Graham", "D",
  "Michael","E", "Capuano", "M",
  "Nita", "M", "Lowey","L",
  "Rosa", "L", "DeLauro", "I",
  "Joseph", "I", "Lieberman", "(J|L)" ,
  "John", "F", "Kerry", "P",
  "Jon", "S", "Corzine", "C",
  "David", "N", "Cicilline", "(R|L|P)",
  "David", "B", "McKinley", "P",
  "James", "R", "Langevin", "P",
  "James", "M", "Inhofe", "N",
  "Charles", "H", "Taylor", "F",
  "Eliot", "L", "Engel", "E",
  "Bobby", "L", "Rush", "E",
  "Gary", "L", "Ackerman", "J",
  "Anthony", "G", "Brown", "J",
  "Peter", "G", "Fitzgerald", "B",
  "John", "J", "Faso", "S",
  "Allyson", "Y", "Schwartz", "D"
)%>%
  transmute(typos = str_c(str_c(first_name, " ", middle_initial_typos, " ", last_name),
                          str_c(last_name, ", ", first_name, " ", middle_initial_typos), sep = "|"),
            correct = paste(first_name, middle_initial, last_name ))





# #Fixes name typo (from DOL_SOL)

#FIXED and added names into miscellaneous tables above

# data$FROM %<>%
#   str_replace("Davis, Arthur", "Davis, Artur") %>%
#   str_replace("Gillibrand, Kirstein", "Gillibrand, Kirsten") %>%
#   str_replace("Leahy, Ted", "Leahy, Patrick") %>%
#   str_replace("Gerlah, Jim", "Gerlach, Jim") %>%
#   str_replace("Obama, Brack", "Obama, Barack") %>%
#   str_replace("Hooley, Darene", "Hooley, Darlene")



# combine typos
typos <- typos_clear %>%
  full_join(typos_first) %>%
  full_join(typos_last) %>%
  full_join(typos_middle) %>%
  full_join(typos_middle_initial) %>%
  full_join(typos_common_name) %>%
  # combine typos with the same correction
  group_by(correct) %>%
  summarise(typos = typos %>% str_c(collapse = "|") ) %>%
  mutate(typos = tolower(typos),
         correct = tolower(correct))




rm(typos_clear, typos_first, typos_last, typos_middle, typos_middle_initial, typos_common_name)

